fixer_name:  
    MSWEP-default:
        data_model: cf
        vars:
            # Automatic conversion to destination grib units
            tprate:
                source: precipitation
                grib: true