plugins:
  source:
    - module: intake_xarray


sources:
  monthly:
    description: EN4 data v4.2.2_g10 version from 1950 to 2022
    driver: netcdf
    metadata:
      source_grid_name: en4
    args:
      urlpath: '{{DATA_PATH}}/EN4/*-1950_2022.nc'
      chunks: 
        time: 12
      xarray_kwargs:
        decode_times: True