sources:
  lra-r100-monthly:
    driver: netcdf
    description: LRA data monthly at r100
    args:
      urlpath: 
        "{{LRA_LUMI}}/ICON/ssp370/r100/monthly/*ssp370_r100_monthly_*.nc"
      chunks: {}
      xarray_kwargs:
        decode_times: true
        combine: by_coords
    metadata:
      source_grid_name: lon-lat
      fixer_name: icon-destine-v1-ssp370-lra
