sources:
  fdb-long:
    args:
      request:
        domain: g
        class: rd
        expver: hz9n
        type: fc
        stream: lwda
        anoffset: 9
        date: 20200120
        time: "0000"
        param: tcc
        levtype: sfc
        step: 0
      data_start_date: 20200120
      data_end_date: 20210101
      chunks: S
      timestep: h
      timestyle: step
    description: FDB data tco399 grid
    driver: gsv
    metadata: 
      fdb_path: /data/users/jost/fdb/fdb-long-mini/config.yaml
      source_grid_name: tco399
