sources:
  fdb-long-2d:
    args:
      request:
        domain: g
        class: rd
        expver: hz9n
        type: fc
        stream: lwda
        anoffset: 9
        date: 20200120
        time: "0000"
        param: 2t
        levtype: sfc
        step: 0
      data_start_date: 20200120
      data_end_date: 20240101
      aggregation: D
      savefreq: h
      timestep: h
      timestyle: step
    description: 'FDB data tco399 grid'
    driver: gsv
    metadata:
      fdb_path: /scratch/project_465000454/igonzalez/fdb-long/config.yaml
      variables: ['sro', 'ssro', 'ci', 'rsn', 'sst', 'swvl1', 'swvl2', 'swvl3', 'swvl4',
                  'tclw', 'tciw', 'sp', 'tcwv', 'stl1', 'sd',
                  'sf', 'sshf', 'slhf', 'msl', 'tcc', '10u', '10v', '2t', '2d', 'ssrd',
                  'stl2', 'lsm', 'strd', 'ssr', 'str', 'tsr', 'ttr', 'ewss', 'nsss',
                  'stl3', 'lgws', 'mgws', 'tisr', 'tp', 'skt', 'stl4','so', 'ocu', 'ocv',
                  'zos', 't20d', 'tav300', 'sav300', 'sithick', 'fdir', 'i10fg', 'tcrw',
                  'tcsw', 'ssrdc', '100u', '100v']
      source_grid_name: tco399
  fdb-long-3d:
    args:
      request:
        domain: g
        class: rd
        expver: hz9n
        type: fc
        stream: lwda
        anoffset: 9
        date: 20200120
        time: "0000"
        param: z
        levtype: pl
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: 20200120
      data_end_date: 20240101
      aggregation: D
      savefreq: h
      timestep: h
      timestyle: step
    description: 'FDB data tco399 grid'
    driver: gsv
    metadata:
      fdb_path: /scratch/project_465000454/igonzalez/fdb-long/config.yaml
      variables: ['z', 't', 'u', 'v', 'w']
      levels: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,700, 850, 925, 1000]
      source_grid_name: tco399
