# one month of data so far
sources:
  hourly-native:
    args:
      request:
        domain: g
        class: rd
        expver: i2hm
        type: fc
        stream: lwda
        date: 19900101
        time: "0000"
        param: 2t
        levtype: sfc
        step: 0
      data_start_date: 19900101T0000
      data_end_date: 19900131T2300
      aggregation: D  # Default aggregation / chunk size
      savefreq: H  # at what frequency are data saved
      timestep: H  # base timestep for step timestyle
      timestyle: step  # variable date or variable step
    description: hourly data on native grid TCo1279 (about 10km). Contains
      tprate(260048), 2t(167), 10u(165), 10v(166), 100u(228246), 100v(228247),
      blh(159), 2d(168), skt(235), sp(134), fsr(244). See fix yaml for derived vars.
    driver: gsv
    metadata: 
      fdb_path: /pfs/lustrep3/scratch/project_465000454/sbeyer/raps_sbeyer/etc/fdb/config.yaml
      eccodes_path: /projappl/project_465000454/jvonhar/aqua/eccodes/eccodes-2.31.2/definitions
      variables: ['tprate', '2t', '10u', '10v', '100u', '100v', 'blh', '2d', 'skt', 'sp', 'fsr']
      source_grid_name: tco1279
      fixer_name: ifs-control
  hourly-1deg:
    args:
      request:
        domain: g
        class: rd
        expver: i2hm
        type: fc
        stream: scda
        date: 19900101
        time: "0000"
        param: sf
        levtype: sfc
        step: 0
      data_start_date: 19900101T0000
      data_end_date: 19900131T2300
      aggregation: D  # Default aggregation / chunk size
      savefreq: H  # at what frequency are data saved
      timestep: H  # base timestep for step timestyle
      timestyle: step  # variable date or variable step
    description: hourly data on r100 grid. Contains tprate(260048), sf(144), 2t(167),
      10u(165), 10v(166), blh(159), sshf(146), slhf(147), ssrd(169), ssr(176), strd(175),
      str(177), ttr(179), e(182), tsr(178), ewss(180), nsss(181), sro(8).
      See fix yaml for derived vars.
    driver: gsv
    metadata: 
      fdb_path: /pfs/lustrep3/scratch/project_465000454/sbeyer/raps_sbeyer/etc/fdb/config.yaml
      eccodes_path: /projappl/project_465000454/jvonhar/aqua/eccodes/eccodes-2.31.2/definitions
      variables: ['tprate', 'sf', '2t', '10u', '10v', 'blh', 'sshf', 'slhf', 'ssrd', 'ssr', 'strd', 'str', 'ttr', 'e', 'tsr', 'ewss', 'nsss', 'sro']
      source_grid_name: lon-lat
      fixer_name: ifs-control
  6hourly-1deg:
    args:
      request:
        domain: g
        class: rd
        expver: i2hm
        type: fc
        stream: scwv
        date: 19900101
        time: '0000'
        param: z
        levtype: pl
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 6  # First available step
      data_start_date: 19900101T0000
      data_end_date: 19900131T1800
      aggregation: D  # Default aggregation / chunk size
      timestep: H  # What one step means
      savefreq: 6H
      timestyle: step
    description: 6hourly data on r100 grid. Contains z(129).
    driver: gsv
    metadata: 
      fdb_path: /pfs/lustrep3/scratch/project_465000454/sbeyer/raps_sbeyer/etc/fdb/config.yaml
      eccodes_path: /projappl/project_465000454/jvonhar/aqua/eccodes/eccodes-2.31.2/definitions
      variables: ['z']
      source_grid_name: lon-lat
  monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: i2hm
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: sd
        levtype: sfc
        step: 0
      data_start_date: '19900101'
      data_end_date: '19900101'
      aggregation: Y  # Default aggregation / chunk size
      savefreq: M
      timestep: H
      timestyle: step
      timeshift: true    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. Contains tprate(260048), 2t(167), tcc(164),
      sd(141), tciw(79), tclw(78), msl(151), tcwv(137), lcc(186), mcc(187), hcc(188).
    driver: gsv
    metadata: 
      fdb_path: /pfs/lustrep3/scratch/project_465000454/sbeyer/raps_sbeyer/etc/fdb/config.yaml
      eccodes_path: /projappl/project_465000454/jvonhar/aqua/eccodes/eccodes-2.31.2/definitions
      variables: ['tprate', '2t', 'tcc', 'sd', 'tciw', 'tclw', 'msl', 'tcwv', 'lcc', 'mcc', 'hcc']
      source_grid_name: lon-lat
      fixer_name: ifs-control
  monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: i2hm
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: t
        levtype: pl
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: '19900101'
      data_end_date: '19900101'
      aggregation: M  # Default aggregation / chunk size
      savefreq: M
      timestep: H
      timestyle: step
      timeshift: true    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. Contains u(131), v(132), t(130), r(157), q(133).
    driver: gsv
    metadata: 
      fdb_path: /pfs/lustrep3/scratch/project_465000454/sbeyer/raps_sbeyer/etc/fdb/config.yaml
      eccodes_path: /projappl/project_465000454/jvonhar/aqua/eccodes/eccodes-2.31.2/definitions
      variables: ['u', 'v', 't', 'r', 'q']
      source_grid_name: lon-lat
