sources:
  test-tco79:
    description: 5km experiment, coupuled with IFS
    driver: yaml_file_cat
    args:
      path: '{{CATALOG_DIR}}/test-tco79.yaml'
  tco79-eORCA1:
    description: tco79-eORCA1 data
    driver: yaml_file_cat
    args:
      path: '{{CATALOG_DIR}}/tco79-eORCA1.yaml'
