sources:
  monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: a0ef
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: 187
        levtype: sfc
        step: 0
      data_start_date: '19900101'
      data_end_date: '19920101'
      aggregation: Y
      savefreq: M
      timestep: H
      timestyle: step
      timeshift: Yes
    driver: gsv
    metadata:
      fdb_path: /scratch/project_465000454/iwagner/a0ef/config.yaml
      eccodes_path: 
        /project/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions
      source_grid_name: tco1279
      variables: [186,228004,151,235055,187,137,78,164,141,188,79]
  monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: a0ef
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: 187
        levtype: pl
        step: 0
        levelist: [1,5,10,20,30,50,70,100,150,200,250,300,400,500,600,700,850,925,1000]
      data_start_date: '19900101'
      data_end_date: '19920101'
      aggregation: M
      savefreq: M
      timestep: H
      timestyle: step
      timeshift: Yes
    driver: gsv
    metadata:
      fdb_path: /scratch/project_465000454/iwagner/a0ef/config.yaml
      eccodes_path: 
        /project/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions
      source_grid_name: tco1279
      variables: [60, 132, 157, 130, 133, 131, 129, 135]
