plugins:
  source:
    - module: intake_xarray

sources:
  nh-daily:
    description: Daily Northern Hemisphere OSI-450 sea-ice data
    driver: netcdf
    metadata:
      source_grid_name: osi-saf-nh
    #cache:
    #  - argkey: urlpath
    #    regex: ''
    #    type: file
    args:
      urlpath: '{{DATA_PATH}}/OSI-SAF/OSI-450/raw/ice_conc_nh*.nc'
      chunks: {}
      xarray_kwargs:
        decode_times: True
  nh-monthly:
    description: Monthly averages of Northern Hemisphere OSI-450 sea-ice data
    driver: netcdf
    metadata:
      source_grid_name: osi-saf-nh
    args:
      urlpath: '{{DATA_PATH}}/OSI-SAF/OSI-450/monthly/ice_conc_nh_ease2-250_cdr_v2p0_monthly_1979-2015.nc' 
      chunks:
        time: 12
      xarray_kwargs:
        decode_times: True
  sh-daily:
    description: Southern hemisphere OSI-450 sea-ice data
    driver: netcdf
    metadata:
      source_grid_name: osi-saf-sh
    #cache:
    #  - argkey: urlpath
    #    regex: ''
    #    type: file
    args:
      urlpath: '{{DATA_PATH}}/OSI-SAF/OSI-450/raw/ice_conc_sh*.nc'
      chunks: {}
      xarray_kwargs:
        decode_times: True
  sh-monthly:
    description: Monthly averages of Southern Hemisphere OSI-450 sea-ice data
    driver: netcdf
    metadata:
      source_grid_name: osi-saf-sh
    args:
      urlpath: '{{DATA_PATH}}/OSI-SAF/OSI-450/monthly/ice_conc_sh_ease2-250_cdr_v2p0_monthly_1979-2015.nc' 
      chunks:
        time: 12
      xarray_kwargs:
        decode_times: True

