paths:
  grids: /work/bb1153/b382075/aqua/grids
  weights: /work/bb1153/b382075/aqua/weights
  areas: /work/bb1153/b382075/aqua/areas

metadata:
  parameters:
    LRA_LUMI:
      type: str
      description: the path of the rsynced LRA data from lumi
      default: /work/bb1153/b382076/LRA-lumi
  
sources:
  IFS-FESOM:
    description: IFS-FESOM NextGEMS pre-final (cycle 4) and LUMI backup
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/catalog/IFS-FESOM/main.yaml"
  IFS:
    description: IFS atmosphere model
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/catalog/IFS/main.yaml"
  IFS-NEMO:
    description: IFS-NEMO coupled model
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/catalog/IFS-NEMO/main.yaml"
  FESOM:
    description: FESOM ocean model
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/catalog/FESOM/main.yaml"
  ICON:
    description: ICON model
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/catalog/ICON/main.yaml"
  MSWEP:
    description: MSWEP_V280 precipitation data
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/catalog/MSWEP/main.yaml"
  ERA5:
    description: ERA5 reanalysis data
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/catalog/ERA5/main.yaml"
  CERES:
    description: CERES-EBAF radiation data
    driver: yaml_file_cat
    args:
      path: "{{CATALOG_DIR}}/catalog/CERES/main.yaml"
  AVISO:
    description: AVISO SSH data
    driver: yaml_file_cat
    args:
      path: "{{CATALOG_DIR}}/catalog/AVISO/main.yaml"
  PHC3:
    description: PHC3 climatology
    driver: yaml_file_cat
    args:
      path: "{{CATALOG_DIR}}/catalog/PHC3/main.yaml"
  WOA18:
    description: World Ocean Atlas climatology
    driver: yaml_file_cat
    args:
      path: "{{CATALOG_DIR}}/catalog/WOA18/main.yaml"
  OSI-SAF:
    description: OSI-SAF sea-ice data
    driver: yaml_file_cat
    args:
      path: "{{CATALOG_DIR}}/catalog/OSI-SAF/main.yaml"
  EN4:
    description: EN4 3D temperature and salinity observational data
    driver: yaml_file_cat
    args:
      path: "{{CATALOG_DIR}}/catalog/EN4/main.yaml"
  GPM:
    description: Global Precipitation Measurement
    driver: yaml_file_cat
    args:
      path: "{{CATALOG_DIR}}/catalog/GPM/main.yaml"
  PSC:
    description: Polar Science Center sea ice volume
    driver: yaml_file_cat
    args:
      path: "{{CATALOG_DIR}}/catalog/PSC/main.yaml"
  ESA-CCI:
    description: ESA-CCI data
    driver: yaml_file_cat
    args:
      path: "{{CATALOG_DIR}}/catalog/ESA-CCI/main.yaml"

