sources:
  PT30M:
    metadata:
      grid: HealPIX
      source_grid_name: icon-healpix
      fixer_name: icon-cycle3
    args:
      #chunks: null
      consolidated: true
      urlpath: 
        /work/bm1235/k203123/NextGEMS_Cycle3.git/experiments/ngc3026/outdata/ngc3026_PT30M_{{
        zoom }}.zarr
    driver: zarr
    parameters:
      zoom:
        allowed:
        - 10
        - 9
        - 8
        - 7
        - 6
        - 5
        - 4
        - 3
        - 2
        - 1
        - 0
        default: 0
        description: zoom resolution of the dataset
        type: int
  PT3H:
    metadata:
      grid: HealPIX
      source_grid_name: icon-healpix
      fixer_name: icon-cycle3
    args:
      #chunks: null
      consolidated: true
      urlpath: 
        /work/bm1235/k203123/NextGEMS_Cycle3.git/experiments/ngc3026/outdata/ngc3026_PT3H_{{
        zoom }}.zarr
    parameters:
      zoom:
        allowed:
        - 10
        - 9
        - 8
        - 7
        - 6
        - 5
        - 4
        - 3
        - 2
        - 1
        - 0
        default: 0
        description: zoom resolution of the dataset
        type: int
    driver: zarr
  P1D:
    args:
      #chunks: null
      consolidated: true
      urlpath: 
        /work/bm1235/k203123/NextGEMS_Cycle3.git/experiments/ngc3026/outdata/ngc3026_P1D_{{
        zoom }}.zarr
    parameters:
      zoom:
        allowed:
        - 10
        - 9
        - 8
        - 7
        - 6
        - 5
        - 4
        - 3
        - 2
        - 1
        - 0
        default: 0
        description: zoom resolution of the dataset
        type: int
    metadata:
      grid: HealPIX
      source_grid_name: icon-healpix
      fixer_name: icon-cycle3
    driver: zarr
  lra-r100-monthly:
    driver: netcdf
    description: LRA data monthly at r100
    args:
      urlpath: 
        /work/bb1153/b382076/LRAv3/ICON/ngc3026/r100/monthly/*ngc3026_r100_monthly_????.nc
      chunks: {}
      xarray_kwargs:
        decode_times: true
    metadata:
      source_grid_name: lon-lat
