sources:
  PT30M:
    args:
      metadata:
        grid: HealPIX
        source_grid_name: icon-healpix
        fixer_name: icon-cycle3
      consolidated: true
      urlpath: 
        /work/bm1235/k203123/NextGEMS_Cycle3.git/experiments/ngc3028/outdata/ngc3028_PT30M_{{
        zoom }}.zarr
    driver: zarr
    parameters:
      zoom:
        allowed:
        - 10
        - 9
        - 8
        - 7
        - 6
        - 5
        - 4
        - 3
        - 2
        - 1
        - 0
        default: 0
        description: zoom resolution of the dataset
        type: int
  PT3H:
    args:
      metadata:
        grid: HealPIX
        source_grid_name: icon-healpix
        fixer_name: icon-cycle3
      consolidated: true
      urlpath: 
        /work/bm1235/k203123/NextGEMS_Cycle3.git/experiments/ngc3028/outdata/ngc3028_PT3H_{{
        zoom }}.zarr
    driver: zarr
    parameters:
      zoom:
        allowed:
        - 10
        - 9
        - 8
        - 7
        - 6
        - 5
        - 4
        - 3
        - 2
        - 1
        - 0
        default: 0
        description: zoom resolution of the dataset
        type: int
  P1D:
    args:
      metadata:
        grid: HealPIX
        source_grid_name: icon-healpix
        fixer_name: icon-cycle3
      consolidated: true
      urlpath: 
        /work/bm1235/k203123/NextGEMS_Cycle3.git/experiments/ngc3028/outdata/ngc3028_P1D_{{
        zoom }}.zarr
    driver: zarr
    parameters:
      zoom:
        allowed:
        - 10
        - 9
        - 8
        - 7
        - 6
        - 5
        - 4
        - 3
        - 2
        - 1
        - 0
        default: 0
        description: zoom resolution of the dataset
        type: int
  lra-r100-monthly:
    driver: netcdf
    description: LRA data monthly at r100
    args:
      urlpath: 
        /work/bb1153/b382076/LRAv3/ICON/ngc3028/r100/monthly/*ngc3028_r100_monthly_????.nc
      chunks: {}
      xarray_kwargs:
        decode_times: true
    metadata:
      source_grid_name: lon-lat
