log_level: DEBUG
log_name: ssh_logger
check_complete_timespan_data: False
check_complete_timespan_models: False
difference_plots: True

# Models for which sea surface height (SSH) variability is to be evaluated.
models:
  - name: IFS-NEMO
    experiment: historical-1990
    source: daily-r025-oce2d
    regrid: r025
    variable: avg_zos
    zoom: 7
    #timespan: ['2020-01-20', '2020-12-31']
    timespan: ['1990-01-21', '1990-06-22']

  # - name: ICON
  #   experiment: ngc3026
  #   source: P1D
  #   regrid: r100 #r005 is computationally demanding and takes over 2 hours.
  #   variable: zos
  #   zoom: 7
  #   timespan: ['2020-01-20', '2021-01-24']
  # - name: FESOM
  #   experiment: tco2559-ng5-cycle3
  #   source: 2D_daily_native
  #   regrid: r025
  #   variable: zos
  #   zoom:
  #   timespan: ['2020-01-21', '2020-12-31']

# This is the model against which other models are compared.
base_model: 
  { name: AVISO,
    experiment: ssh-L4,
    source: daily,
    regrid: r025
  }

# ONLY FOR ICON: Flags for northern and southern boundaries to mask out specific latitudes.
# As AVISO does not have data under the sea ice, which ICON does, to make the datasets comparable - SSH under sea ice for ICON can be masked out.
mask_northern_boundary: true
mask_southern_boundary: true
northern_boundary_latitude: 70
southern_boundary_latitude: -62

# As default one timespan for all models will be set but this can be overwritten for each model by entering the timespan in the individual model configurations. This timespan will be applied to the AVISO observation data.
timespan: {start: '2020-01-20', end: '2021-12-31'}
#timespan: {start: '2020-01-21', end: '2021-07-22'}


# These are options to adjust subplots visualizations.
subplot_options:
  { scale_min: 0.1,
    scale_max: 0.4,
    cmap: viridis
  } 
  
# Please specify the path to the directory where the outputs should be saved. If output directory/ folder does not exist, another directory called output will be created in your current working directory.
output_directory: /projappl/project_465000454/sunnyjal/AQUA/diagnostics/ssh/output/


# This is the current dask configuration which works for the inputs above. It could be adjusted based on the system this application is run.
dask_cluster:
  n_workers: 16
  threads_per_worker: 1

