sources:
  monthly-healpix-2d:
    args:
      request:
        domain: g
        class: rd
        expver: a0ef
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: 187
        levtype: sfc
        step: 0
      data_start_date: '19900101'
      data_end_date: '19911231'
      aggregation: Y
      savefreq: M
      timestep: H
      timestyle: step
      timeshift: Yes
    driver: gsv
    metadata:
      fdb_path: /scratch/project_465000454/iwagner/a0ef/config.yaml
      eccodes_path: 
        /project/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions
      source_grid_name: ifs-healpix
      variables: [186, 228004, 151, 235055, 187, 137, 78, 164, 141, 188, 79]
  monthly-healpix-3d:
    args:
      request:
        domain: g
        class: rd
        expver: a0ef
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: 187
        levtype: pl
        step: 0
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
      data_start_date: '19900101'
      data_end_date: '19911231'
      aggregation: M
      savefreq: M
      timestep: H
      timestyle: step
      timeshift: Yes
    driver: gsv
    metadata:
      fdb_path: /scratch/project_465000454/iwagner/a0ef/config.yaml
      eccodes_path: 
        /project/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions
      levels: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600, 700, 850, 925, 1000]
      source_grid_name: ifs-healpix
      variables: [60, 132, 157, 130, 133, 131, 129, 135]
  oce-monthly-healpix-2d:
    args:
      request:
        domain: g
        class: rd
        expver: a0ef
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: 263101
        levtype: o2d
        step: 0
      data_start_date: '19900101'
      data_end_date: '19911231'
      aggregation: M
      savefreq: M
      timestep: H
      timestyle: step
      timeshift: Yes
    driver: gsv
    metadata:
      fdb_path: /scratch/project_465000454/iwagner/a0ef/config.yaml
      eccodes_path: 
        /project/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions
      source_grid_name: nemo-healpix
      variables: [263101, 263001, 263122, 263121, 263100]
  oce-monthly-healpix-3d:
    args:
      request:
        domain: g
        class: rd
        expver: a0ef
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: 187
        levtype: o3d
        step: 0
        levelist: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
          19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
          37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
          55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
          73, 74, 75]
      data_start_date: '19900101'
      data_end_date: '19911231'
      aggregation: M
      savefreq: M
      timestep: H
      timestyle: step
      timeshift: Yes
    driver: gsv
    metadata:
      fdb_path: /scratch/project_465000454/iwagner/a0ef/config.yaml
      eccodes_path: 
        /project/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions
      levels: [0.5057600140571594, 1.5558552742004395, 2.6676816940307617, 3.8562798500061035,
                5.140361309051514, 6.543033599853516, 8.09251880645752, 9.822750091552734,
                11.773679733276367, 13.99103832244873, 16.52532196044922, 19.42980194091797,
                22.75761604309082, 26.558300018310547, 30.874561309814453, 35.740203857421875,
                41.180023193359375, 47.21189498901367, 53.85063552856445, 61.11283874511719,
                69.02168273925781, 77.61116027832031, 86.92942810058594, 97.04131317138672,
                108.03028106689453, 120.0,  133.07582092285156, 147.40625,
                163.16445922851562, 180.5499267578125, 199.7899627685547, 221.14117431640625,
                244.890625, 271.35638427734375, 300.88751220703125, 333.8628234863281,
                370.6884765625, 411.7938537597656, 457.6256103515625, 508.639892578125,
                565.2922973632812, 628.0260009765625, 697.2586669921875, 773.3682861328125,
                856.678955078125, 947.4478759765625, 1045.854248046875, 1151.9912109375,
                1265.8614501953125, 1387.376953125, 1516.3636474609375, 1652.5684814453125,
                1795.6707763671875, 1945.2955322265625, 2101.026611328125, 2262.421630859375,
                2429.025146484375, 2600.38037109375, 2776.039306640625, 2955.5703125,
                3138.56494140625, 3324.640869140625, 3513.445556640625, 3704.65673828125,
                3897.98193359375, 4093.15869140625, 4289.95263671875, 4488.15478515625,
                4687.5810546875, 4888.06982421875, 5089.478515625, 5291.68310546875,
                5494.5751953125, 5698.060546875, 5902.0576171875 ]
      source_grid_name: nemo-healpix
      variables: [263500, 263501, 263505, 263506, 263507]
  lra-r100-monthly:
    driver: netcdf
    description: LRA data monthly at r100
    args:
      urlpath: 
        /pfs/lustrep3/projappl/project_465000454/padavini/LRA/IFS-NEMO/spinup-1990-fracice/r100/monthly/*spinup-1990-fracice_r100_monthly_*.nc
      chunks: {}
      xarray_kwargs:
        decode_times: true
    metadata:
      source_grid_name: lon-lat
