sources:
  test-healpix:
    description: Healpix test data
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/test-healpix.yaml"
  test-r2b0:
    description: ICON r2b0 test data
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/test-r2b0.yaml"