  plugins:
    source:
      - module: intake_xarray
  sources:
    daily-original-2d:
      description: 2d test data
      driver: netcdf
      args:
        urlpath: 
          - /scratch/project_465000454/sbeyer/rundir_vulcano/tco1279l137/i2hm/hres/cray.craympich/lum.cce.sp/h744.N144.T4096xt4xh1+ioT512xt4.nextgems_6h.i16r0w24.htco1279-1990-4460719/ssh.fesom.1990.nc
          - /scratch/project_465000454/sbeyer/rundir_vulcano/tco1279l137/i2hm/hres/cray.craympich/lum.cce.sp/h744.N144.T4096xt4xh1+ioT512xt4.nextgems_6h.i16r0w24.htco1279-1990-4460719/a_ice.fesom.1990.nc
        chunks: 
          time: -1
        xarray_kwargs:
          decode_times: true
    monthly-original-2d:
      description: 2d test data
      driver: netcdf
      args:
        urlpath: 
          - /scratch/project_465000454/sbeyer/rundir_vulcano/tco1279l137/i2hm/hres/cray.craympich/lum.cce.sp/h744.N144.T4096xt4xh1+ioT512xt4.nextgems_6h.i16r0w24.htco1279-1990-4460719/sss.fesom.1990.nc
          - /scratch/project_465000454/sbeyer/rundir_vulcano/tco1279l137/i2hm/hres/cray.craympich/lum.cce.sp/h744.N144.T4096xt4xh1+ioT512xt4.nextgems_6h.i16r0w24.htco1279-1990-4460719/sst.fesom.1990.nc
        chunks: 
          time: -1
        xarray_kwargs:
          decode_times: true
    monthly-original-3d:
      description: 3d test data
      driver: netcdf
      args:
        urlpath: 
          - /scratch/project_465000454/sbeyer/rundir_vulcano/tco1279l137/i2hm/hres/cray.craympich/lum.cce.sp/h744.N144.T4096xt4xh1+ioT512xt4.nextgems_6h.i16r0w24.htco1279-1990-4460719/salt.fesom.1990.nc
          - /scratch/project_465000454/sbeyer/rundir_vulcano/tco1279l137/i2hm/hres/cray.craympich/lum.cce.sp/h744.N144.T4096xt4xh1+ioT512xt4.nextgems_6h.i16r0w24.htco1279-1990-4460719/temp.fesom.1990.nc
        chunks: 
          time: -1
        xarray_kwargs:
          decode_times: true