plugins:
  source:
    - module: intake_xarray

sources:
  monthly:
    description: sea ice thickness monthly data
    driver: netcdf
    metadata:
      fixer_name: GIOMAS
      source_grid_name: psc-giomas
    args:
      chunks:
        time: 1
        use_cftime: True
      xarray_kwargs:
        decode_times: True
      urlpath:
      - /projappl/project_465000454/data/AQUA/datasets/PSC/GIOMAS/sivol_r1i1p1_mon_197901-202212_GCCS360x276.new.nc