# Choice of interface
interface: AQUA
# Choice of model name. It is printed in the output table
model:
  name: ClimateDT

dirs:
  exp: /pfs/lustrep3/projappl/project_465000454/data/AQUA/diagnostics/ecmean
  clm: /users/padavini/AQUA/diagnostics/ecmean/ECmean4/ecmean/climatology
  tab: /pfs/lustrep3/projappl/project_465000454/padavini/ecmean/output/YAML
  fig: /pfs/lustrep3/projappl/project_465000454/padavini/ecmean/output/PDF

global:
  atm_vars: [tas, psl, pr, evspsbl, pme, clt, cll, clm, clh,
            pr_oce, pme_oce, pr_land, pme_land,
            rsnt, rlnt, net_toa, rsns, rlns, hfss, hfls]
  oce_vars: [tos, sos]
  ice_vars: [siconc]
  tab_vars: []
  regions: ['Global', 'North Midlat', 'Tropical', 'South Midlat']
  seasons: ['ALL', 'DJF', 'JJA']

PI:
  2d_vars:
    field: [net_sfc, tas, pr, psl, tauu, tauv]
  3d_vars:
    field: [ta, ua, va, hus]
  oce_vars:
    field: [tos, sos]
  ice_vars:
    field: [siconc]
  regions: ['Global', 'North Midlat', 'Tropical', 'South Midlat']
  seasons: ['ALL', 'DJF', 'JJA']
  resolution: r360x180

