# machine dependent configuration file for AQUA
# so far nothing is really strict
machine: mafalda

reader: 
  catalog: '{configdir}/{machine}/catalog.yaml'
  regrid: '{configdir}/{machine}/regrid.yaml'
  fixer: '{configdir}/fixes.yaml'


