# machine dependent configuration file for AQUA
# so far nothing is really strict
machine: lumi

reader: 
  catalog: '{configdir}/machines/{machine}/catalog.yaml'
  fixer: '{configdir}/fixes'

cdo:  # CDO path is found automatically with which if not specified here
  levante: /home/m/m214003/local/bin/cdo # CDO 2.2.0 by Uwe Schulzweida (HEALPix support)

