sources:
  lra-r100-monthly:
    driver: netcdf
    description: LRA data monthly at r100
    args:
      urlpath: /work/bb1153/b382076/LRA-dev/IFS/control-1950-devcon/r100/monthly/*control-1950-devcon_r100_monthly_????.nc
      chunks: {}
      xarray_kwargs:
        decode_times: true