sources:
  lra-r100-monthly:
    driver: netcdf
    description: LRA data monthly at r100
    args:
      urlpath: /work/bb1153/b382076/LRA-dev/IFS/historical-1990-devcon/r100/monthly/*historical-1990-devcon_r100_monthly_????.nc
      chunks: {}
      xarray_kwargs: