plugins:
  source:
  - module: intake_xarray
  - module: gribscan
sources:
  ICMGG_atm2d:
    driver: zarr
    description: original 2d output
    metadata:
      source_grid_name: tco1279
      fix_names: ifs-default
    args:
      consolidated: false
      urlpath:
        #reference::/work/bm1235/a270046/cycle2-sync/tco1279-orca025/nemo_deep/ICMGGc2/json.dir/atm2d.json
      - reference::/work/bm1344/AWI/nextGEMS_Cycle2_IFS_concat/tco1279-orca025/nemo_deep/varfiles_all/json.dir/atm2d.json
  ICMU_atm2d:
    driver: zarr
    description: original 2d output (lnsp)
    metadata:
      source_grid_name: tco1279
      fix_names: ifs-default
    args:
      consolidated: false
      urlpath:
        #reference::/work/bm1235/a270046/cycle2-sync/tco1279-orca025/nemo_deep/ICMUAc2/json.dir/atm2d.json
      - reference::/work/bm1344/AWI/nextGEMS_Cycle2_IFS_concat/tco1279-orca025/nemo_deep/varfiles_all/json.dir/atm2d.json
  ICMU_atm3d:
    driver: zarr
    description: original 3d output
    metadata:
      source_grid_name: tco1279
    args:
      consolidated: false
      urlpath:
        #reference::/work/bm1235/a270046/cycle2-sync/tco1279-orca025/nemo_deep/ICMUAc2/json.dir/atm3d.json
      - reference::/work/bm1344/AWI/nextGEMS_Cycle2_IFS_concat/tco1279-orca025/nemo_deep/varfiles_all/json.dir/atm3d.json
  lra-r100-monthly:
    driver: netcdf
    description: LRA data monthly at r100
    metadata:
      source_grid_name: lon-lat
    args:
      urlpath: 
        /work/bb1153/b382076/LRA-cycle2/IFS/tco1279-orca025/r100/monthly/*tco1279-orca025_r100_monthly_????.nc
      chunks: {}
      xarray_kwargs:
        decode_times: true
