plugins:
  source:
  - module: intake_xarray
  - module: gribscan
sources:
  2D_1h_native:
    driver: zarr
    args:
      consolidated: false
      urlpath: 
        reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_1h6h_native/json.dir/atm2d.json
    metadata:
      source_grid_name: tco1279
      fixer_name: ifs-default
  3D_1h_native:
    driver: zarr
    args:
      consolidated: false
      urlpath: 
        reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_1h6h_native/json.dir/atm3d.json
    metadata:
      source_grid_name: tco1279
  2D_monthly_native:
    driver: zarr
    args:
      consolidated: false
      urlpath: 
        reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_monthly_native/json.dir/atm2d.json
    metadata:
      source_grid_name: tco1279
      fixer_name: ifs-cycle3
  3D_monthly_native:
    driver: zarr
    args:
      consolidated: false
      urlpath: 
        reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_monthly_native/json.dir/atm3d.json
    metadata:
      source_grid_name: tco1279
  2D_1h_0.25deg:
    driver: zarr
    args:
      consolidated: false
      urlpath: 
        reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_1h6h_0.25deg/json.dir/atm2d.json
    metadata:
      source_grid_name: multio-r025
      fixer_name: ifs-cycle3
  3D_1h_0.25deg:
    driver: zarr
    args:
      consolidated: false
      urlpath: 
        reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_1h6h_0.25deg/json.dir/atm3d.json
    metadata:
      source_grid_name: multio-r025
  2D_monthly_0.25deg:
    driver: zarr
    args:
      consolidated: false
      urlpath: 
        reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_monthly_0.25deg/json.dir/atm2d.json
    metadata:
      source_grid_name: multio-r025
      fixer_name: ifs-cycle3
  3D_monthly_0.25deg:
    driver: zarr
    args:
      consolidated: false
      urlpath: 
        reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_monthly_0.25deg/json.dir/atm3d.json
    metadata:
      source_grid_name: multio-r025
  # 2D_1h_1deg:
  #   driver: zarr
  #   args:
  #     consolidated: false
  #     urlpath: 
  #       reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_1h6h_1deg/json.dir/atm2d.json
  # 3D_1h_1deg:
  #   driver: zarr
  #   args:
  #     consolidated: false
  #     urlpath: 
  #       reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_1h6h_1deg/json.dir/atm3d.json
  # 2D_monthly_1deg:
  #   driver: zarr
  #   args:
  #     consolidated: false
  #     urlpath: 
  #       reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_monthly_1deg/json.dir/atm2d.json
  # 3D_monthly_1deg:
  #   driver: zarr
  #   args:
  #     consolidated: false
  #     urlpath: 
  #       reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_monthly_1deg/json.dir/atm3d.json
  # WAM_1h_native:
  #   driver: zarr
  #   args:
  #     consolidated: false
  #     urlpath: 
  #       reference::/work/bm1235/b381679/IFS_cycle3/9km_nemo/gribscan_1h_wam/json.dir/atm2d.json
  lra-r100-monthly:
    driver: netcdf
    description: LRA data monthly at r100
    args:
      urlpath: 
        /work/bb1153/b382076/LRA-cycle3/IFS/tco1279-orca025-cycle3/r100/monthly/*tco1279-orca025-cycle3_r100_monthly_????.nc
      chunks: {}
      xarray_kwargs:
        decode_times: true
    metadata:
      source_grid_name: lon-lat