sources:
  hourly-healpix-2d:
    args:
      request:
        date: 19900101
        time: '0000'
        param: 10u
        levtype: sfc
        step: 0
      data_start_date: 19900101T0000
      data_end_date: 19901231T2300
      aggregation: D  # Default aggregation / chunk size
      savefreq: H
      timestyle: date
      #timeshift: Yes    # shift time of resulting xarray by this amount
    description: ICON historical development run refactored into a simpler FDB
    driver: gsv
    metadata: 
      fdb_path: /projappl/project_465000454/experiments/ig01/config.yaml
      eccodes_path: /projappl/project_465000454/jvonhar/aqua/eccodes/eccodes-2.32.0/definitions
      variables: ['10u', '10v', '2t']
      source_grid_name: icon-healpix-dev
      fixer_name: icon-destine