data:
  model:  "IFS-NEMO"
  exp:    "historical-1990"
  source: "lra-r100-monthly"

  model_obs:  "ERA5"
  exp_obs:    "era5"
  source_obs: "monthly"

diagnostic_attributes:
  variables_no_plev: ['2t']
  variables_with_plev: ['u']
  plev: null # You can specify a pressure level here
  statistic: "mean" #Â Valid options are: 'mean', 'max', 'min', 'diff', and 'std'.
  seasonal_bias: False
  seasons: False
  compare_datasets_plev: True
  plot_map_with_stats: False
  start_date1: "1990-01-01"
  end_date1: "2004-11-01"
  start_date2: "1990-01-01" 
  end_date2: "2020-12-31"

path:
  path_to_output: "/work/bb1153/b382257/aqua_output/deliverable_d370733/atmglobalmean/"

# Here you can specify the colorbar limits for each variable
# If you don't specify them, the colorbar limits will be automatically calculated
# based on the data.
seasonal_bias:
  2t:
    vmin: -15
    vmax: 15
  avg_tos:
    vmin: -10
    vmax: 10
  msl:
    vmin: -1000
    vmax: 1000
  mtnlwrf:
    vmin: -40
    vmax: 40
  mtpr:
    vmin: -8
    vmax: 8

compare_datasets_plev:
  t:
    vmin: -20
    vmax: 20
  u:
    vmin: -18
    vmax: 18
  q:
    vmin: -0.002
    vmax: 0.002
    
  plev_min: 1000
  plev_max: 100000