paths:
  grids: ./AQUA_tests/grids
  weights: ./AQUA_tests/weights
  areas: ./AQUA_tests/weights

sources:
  FESOM:
    description: FESOM ocean model
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/catalog/FESOM/main.yaml"
  IFS:
    description: IFS atmospheric model
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/catalog/IFS/main.yaml"
  ICON:
    description: ICON atmospheric model
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/catalog/ICON/main.yaml"
  NEMO:
    description: NEMO oceanic model
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/catalog/NEMO/main.yaml"

# available grids, not worth to become machine independent
# extra is an extra special cdo command to be applied before generating the weights
grids:
  # IFS
  tco79-testmask:
    path:  
      2d: $grids/IFS/tco79_grid.nc
      2dm: $grids/IFS/tco79_grid_masked.nc
    vert_coord: ["2d", "2dm"]
    masked: 
      vars: ["2t"] # for testing purposes
  tco79-nn:
      path: $grids/IFS/tco79_grid.nc
      regrid_method: 'nn'
  # FESOM
  test-pi-2d:
    path: $grids/pi_griddes_nodes_IFS.nc
    #space_coord: [nod2]
    extra:
    - -setgrid,$grids/pi_griddes_nodes_IFS.nc
    - -selname,cell_area
  test-pi-3d:
    path:
      nz1: $grids/pi_fesom_mask_nz1.nc
      nz: $grids/pi_fesom_mask_nz.nc
    space_coord: [nod2]
    vert_coord: [nz1, nz]
    extra:
    - -setgrid,$grids/pi_griddes_nodes_IFS.nc
  # ICON
  test-healpix: {path: $grids/icon_healpix0.nc} #space_coord: [x]
  test-r2b0: {path: ./AQUA_tests/models/ICON/test-lowres/r2b0.nc} #space_coord: [cell]
  test-eORCA1-3d:
    path: 
      level: $grids/NEMO/test-eorca1_3D.nc
    #vert_coord: ["level"]
    extra: 
      - -selname,dummy