sources:
  monthly-hpz7-atm2d: &base-default
    args: &args-default
      request: &request-default
        class: d1
        dataset: climate-dt
        activity: HighResMIP
        experiment: cont
        generation: 1
        model: IFS-NEMO
        realization: 1
        resolution: standard
        expver: hs3l
        type: fc
        stream: clmn
        year: 1990
        month: 1
        param: 228004
        levtype: sfc
      data_start_date: 19900101T0000
      data_end_date: 20091231T0000
      chunks: MS  # Default time chunk size
      savefreq: MS  # at what frequency are data saved
      timestep: h  # base timestep for step timestyle
      timestyle: yearmonth  # variable date or variable step
    description: monthly 2D atmospheric data on healpix grid (zoom=7, h128).
    driver: gsv
    metadata: &metadata-default
      fdb_home: /scratch/project_465000454/xpedruzo/ClimDT_399_runs/hs3l_cont/fdb/healpix
      fdb_path: 
        /scratch/project_465000454/xpedruzo/ClimDT_399_runs/hs3l_cont/fdb/healpix/etc/fdb/config.yaml
      eccodes_path: /projappl/project_465000454/jvonhar/aqua/eccodes/eccodes-2.32.2/definitions
      variables: [175, 176, 168, 228004, 228129, 228050, 228235, 235055, 177, 178,
        179, 211, 212, 228, 186, 148, 228089, 180, 181, 182, 187, 195, 196, 228021,
        183, 188, 207, 228090, 235, 236, 208, 209, 210, 228029, 147, 169, 8, 9, 166,
        170, 34, 31, 33, 78, 79, 142, 144, 146, 165, 139, 141, 164, 134, 151, 159,
        40, 41, 42, 137, 39]
      source_grid_name: hpz7-nested
      fixer_name: ifs-nemo-destine-v2-monthly

  monthly-hpz7-atm3d:
    <<: *base-default
    description: monthly 2D atmospheric data on healpix grid (zoom=7, h128).
    args:
      <<: *args-default
      request:
        <<: *request-default
        param: 131
        levtype: pl
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
    metadata:
      <<: *metadata-default
      levels: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600, 700,
        850, 925, 1000]
      variables: [247, 135, 60, 248, 129, 76, 157, 75, 131, 246, 133, 132, 130]
  lra-r100-monthly:
    driver: netcdf
    description: LRA data monthly at r100
    args:
      urlpath: 
        /pfs/lustrep3/projappl/project_465000454/data/AQUA/LRA/IFS-NEMO/hs3l-control-1990/r100/monthly/*hs3l-control-1990_r100_monthly_*.nc
      chunks: {}
      xarray_kwargs:
        decode_times: true
        combine: by_coords
    metadata:
      source_grid_name: lon-lat

