experiments:

diagnostics:
    Gregory Plot: [global_time_series_gregory, timeseries.gregory_plot]
    Time series: [global_time_series_timeseries, global_time_series_IFS, timeseries.timeseries]
    Seasonal cycle: [global_time_series_seasonalcycle, timeseries.seasonalcycle]
    Performance indices: [PI4, global_mean_]
    Radiation: [radiation., boxplot_, gregory_plot_ifs, gregory_plot_icon, toa_mean_biases_, timeseries_ifs, timeseries_icon]
    Bias maps, horizontal: [global_biases.total_bias_map, global_biases.seasonal_bias_map]
    Bias maps, vertical: global_biases.vertical_bias
    Global maps: [Statistics_maps, atmglobalmean.statistics_maps]
    Seasonal bias: [Seasonal_Bias_Plot, atmglobalmean.seasonal_bias]
    Vertical biases: [Vertical_biases, atmglobalmean.vertical_bias]
    Tropical Rainfall: trop_rainfall
    Teleconnections: teleconnections
    Ocean time series:
        - monthly_time_series_
        - Ocean_time_series
        - ea_time_series
        - Ocean_hovmoller_plot
        - _hovmoller_plot
    Ocean trends:
        - zonal_mean_trend
        - multilevel_t_s_trend
    Ocean stratification and MLD:
        - _stratification_
        - MLD_
    SSH variability: ssh.
    Sea Ice: seaice.
