#IFS-FESOM storyline (control runs) from 2017
sources:
  hourly-hpz7-atm2d: &base-default
    args: &args-default
      request: &request-default
        class: d1
        dataset: climate-dt
        activity: story-nudging
        experiment: cont
        generation: 1
        model: IFS-FESOM
        realization: 1
        resolution: standard
        expver: '0001'
        type: fc
        stream: clte
        date: 20170101
        time: '0000'
        param: 167
        levtype: sfc
        step: 0
      data_start_date: 20170101T0000
      data_end_date: auto
      aggregation: D  # Default aggregation / chunk size
      savefreq: h  # at what frequency are data saved
      timestep: h  # base timestep for step timestyle
      timestyle: date  # variable date or variable step
    #description: hourly data on native grid Tco2559 (about 5km).
    driver: gsv
    metadata: &metadata-default
      fdb_home: /users/lrb_465000454_fdb
      fdb_path: /users/lrb_465000454_fdb/etc/fdb/config.yaml
      eccodes_path: /projappl/project_465000454/jvonhar/aqua/eccodes/eccodes-2.32.5/definitions
      variables: [78, 79, 134, 137, 141, 148, 151, 159, 164, 165, 166, 167, 168, 186,
        187, 188, 235, 260048, 8, 9, 144, 146, 147, 169, 175, 176, 177, 178, 179,
        180, 181, 182, 212, 228]
      source_grid_name: hpz7-nested
      fixer_name: ifs-destine-v1

  hourly-hpz7-atm3d:
    <<: *base-default
    description: hourly 3D atmospheric data on healpix grid (zoom=7, h128).
    args:
      <<: *args-default
      aggregation: 6h
      request:
        <<: *request-default
        param: 129
        levtype: pl
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
    metadata:
      <<: *metadata-default
      levels: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600, 700,
        850, 925, 1000]
      variables: [129, 130, 131, 132, 133, 135, 157, 246]
      source_grid_name: hpz7-nested

  hourly-hpz9-atm2d:
    <<: *base-default
    description: hourly 3D atmospheric data on healpix grid (zoom=9, h512).
    args:
      <<: *args-default
      request:
        <<: *request-default
        param: 129
        levtype: sfc
        resolution: high
    metadata:
      <<: *metadata-default
      source_grid_name: hpz9-nested

  hourly-hpz9-atm3d:
    <<: *base-default
    description: hourly 3D atmospheric data on healpix grid (zoom=9, h512).
    args:
      <<: *args-default
      aggregation: 6h
      request:
        <<: *request-default
        param: 129
        levtype: pl
        resolution: high
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
    metadata:
      <<: *metadata-default
      levels: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600, 700,
        850, 925, 1000]
      variables: [129, 130, 131, 132, 133, 135, 157, 246]
      source_grid_name: hpz9-nested

  daily-hpz7-oce2d:
    <<: *base-default
    description: daily 2D oceanic data on healpix grid (zoom=7, h128).
    args:
      <<: *args-default
      aggregation: MS
      savefreq: D
      request:
        <<: *request-default
        resolution: standard
        param: 263004
        levtype: o2d
    metadata:
      fdb_path: /users/lrb_465000454_fdb/etc/fdb/config.yaml
      variables: [263000, 263001, 263002, 263003, 263004,
        263100, 263101, 263124]
      source_grid_name: fesom-hpz7-nested

  daily-hpz7-oce3d:
    <<: *base-default
    description: daily 3D oceanic data on healpix grid (zoom=7, h128).
    args:
      <<: *args-default
      aggregation: D
      savefreq: D
      request:
        <<: *request-default
        resolution: standard
        levtype: o3d
        levelist: [
          1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
          26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
          50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]
    metadata:
      <<: *metadata-default
      fdb_path:   /users/lrb_465000454_fdb/etc/fdb/config.yaml
      levels: [ 2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5,
    52.5, 57.5, 62.5, 67.5, 72.5, 77.5, 82.5, 87.5, 92.5, 97.5,
    105, 115, 125, 135, 145, 155, 165, 175, 185, 195, 210, 230,
    250, 270, 290, 320, 360, 400, 440, 480, 520, 560, 600, 640,
    710, 810, 950, 1110, 1255, 1415, 1600, 1810, 2035, 2275, 2525,
    2775, 3025, 3275, 3525, 3775, 4025, 4275, 4525, 4775, 5025,
    5275, 5525, 5825, 6175]
      variables: [263500, 263501, 263505, 263506, 263507]
      source_grid_name: fesom-hpz7-nested-3d

  daily-hpz9-oce2d:
    <<: *base-default
    description: daily 2D oceanic data on healpix grid (zoom=9, h1024).
    args:
      <<: *args-default
      aggregation: MS
      savefreq: D
      request:
        <<: *request-default
        resolution: high
        data_start_date: 20180101T0000
        levtype: o2d
    metadata:
      fdb_path: /users/lrb_465000454_fdb/etc/fdb/config.yaml
      variables: [263000, 263001, 263002, 263003, 263004,
        263100, 263101, 263124]
      source_grid_name: fesom-hpz9-nested

  daily-hpz9-oce3d:
    <<: *base-default
    description: daily 3D oceanic data on healpix grid (zoom=9, h1024).
    args:
      <<: *args-default
      aggregation: D
      savefreq: D
      request:
        <<: *request-default
        resolution: high
        data_start_date: 20180101T0000
        levtype: o3d
        levelist: [
          1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
          26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
          50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]
    metadata:
      <<: *metadata-default
      fdb_path:   /users/lrb_465000454_fdb/etc/fdb/config.yaml
      levels: [ 2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5,
    52.5, 57.5, 62.5, 67.5, 72.5, 77.5, 82.5, 87.5, 92.5, 97.5,
    105, 115, 125, 135, 145, 155, 165, 175, 185, 195, 210, 230,
    250, 270, 290, 320, 360, 400, 440, 480, 520, 560, 600, 640,
    710, 810, 950, 1110, 1255, 1415, 1600, 1810, 2035, 2275, 2525,
    2775, 3025, 3275, 3525, 3775, 4025, 4275, 4525, 4775, 5025,
    5275, 5525, 5825, 6175]
      variables: [263500, 263501, 263505, 263506, 263507]
      source_grid_name: fesom-hpz9-nested-3d

  hourly-native-atm2d:
    <<: *base-default
    description: hourly 2D atmospheric data on native grid TCo1279 (about 10km).
    args:
      <<: *args-default
      aggregation: 6H
      request:
        <<: *request-default
        levtype: sfc
        resolution: high
    metadata:
      <<: *metadata-default
      fdb_path: /users/lrb_465000454_fdb/native/etc/fdb/config.yaml
      source_grid_name: tco1279

  hourly-native-atm3d:
    <<: *base-default
    description: hourly 3D atmospheric data on native grid TCo1279 (about 10km).
    args:
      <<: *args-default
      aggregation: H
      request:
        <<: *request-default
        levtype: pl
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
    metadata:
      <<: *metadata-default
      levels: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600, 700,
        850, 925, 1000]
      variables: [129, 130, 131, 132, 133, 135, 157, 246]
      source_grid_name: tco1279

  # OCEANIC NATIVE IS NOT READ BY THE GSV RETRIEVER
  # hourly-native-oce2d:
  #   <<: *base-default
  #   description: hourly 2D ocean data on native grid ng5 (about 10km).
  #   args:
  #     <<: *args-default
  #     aggregation: 6H
  #     request:
  #       <<: *request-default
  #       levtype: o2d
  #       resolution: high
  #   metadata:
  #     <<: *metadata-default
  #     fdb_path: /users/lrb_465000454_fdb/native/etc/fdb/config.yaml
  #     variables: [263000, 263001, 263002, 263003, 263004,
  #        263100, 263101, 263124]
  #     #variables: [263124]
  #     source_grid_name: ng5-nodes-2d


  # hourly-native-oce3d:
  #   <<: *base-default
  #   description: hourly 3D oceanic data on native grid ng5 (about 10km).
  #   args:
  #     <<: *args-default
  #     aggregation: 6H
  #     request:
  #       <<: *request-default
  #       levtype: o3d
  #       levelist: [
  #         1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
  #         26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
  #         50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]
  #   metadata:
  #     <<: *metadata-default
  #     levels: [ 2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5,
  #   52.5, 57.5, 62.5, 67.5, 72.5, 77.5, 82.5, 87.5, 92.5, 97.5,
  #   105, 115, 125, 135, 145, 155, 165, 175, 185, 195, 210, 230,
  #   250, 270, 290, 320, 360, 400, 440, 480, 520, 560, 600, 640,
  #   710, 810, 950, 1110, 1255, 1415, 1600, 1810, 2035, 2275, 2525,
  #   2775, 3025, 3275, 3525, 3775, 4025, 4275, 4525, 4775, 5025,
  #   5275, 5525, 5825, 6175]
  #     variables: [263500, 263501, 263505, 263506, 263507]
  #     source_grid_name: ng5-nodes-3d