plugins:
  source:
  - module: intake_xarray
sources:
  # elem_grid:
  #   args:
  #     urlpath: ./AQUA_tests/grids/pi_griddes_elems_IFS.nc
  #   driver: netcdf
  # node_grid:
  #   args:
  #     urlpath: ./AQUA_tests/grids/pi_griddes_nodes_IFS.nc
  #   driver: netcdf
  original_2d:
    metadata:
      source_grid_name: test-pi-2d
      fixer_name: FESOM-default
    args:
      chunks:
        time: 1
      urlpath:
      - ./AQUA_tests/models/FESOM/short/a_ice.fesom.1985.nc
      - ./AQUA_tests/models/FESOM/short/a_ice.fesom.1986.nc
      - ./AQUA_tests/models/FESOM/short/MLD2.fesom.1985.nc
      - ./AQUA_tests/models/FESOM/short/MLD2.fesom.1986.nc
      - ./AQUA_tests/models/FESOM/short/sst.fesom.1985.nc
      - ./AQUA_tests/models/FESOM/short/sst.fesom.1986.nc
    description: original 2d output
    driver: netcdf
  original_2d_fix:
    metadata:
      source_grid_name: test-pi-2d
      fixer_name: FESOM-test
    args:
      chunks:
        time: 1
      urlpath:
      - ./AQUA_tests/models/FESOM/short/a_ice.fesom.1985.nc
      - ./AQUA_tests/models/FESOM/short/MLD2.fesom.1985.nc
    description: original 2d output
    driver: netcdf
  original_3d:
    metadata:
      fixer_name: FESOM-default
      source_grid_name: test-pi-3d
    args:
      chunks:
        nz: 1
        nz1: 1
        time: 1
      urlpath:
      - ./AQUA_tests/models/FESOM/short/temp.fesom.1985.nc
      - ./AQUA_tests/models/FESOM/short/temp.fesom.1986.nc
      - ./AQUA_tests/models/FESOM/short/w.fesom.1985.nc
      - ./AQUA_tests/models/FESOM/short/w.fesom.1986.nc
    description: original 3d output
    driver: netcdf
