model: IFS-NEMO 
exp: historical-1990
source: lra-r100-monthly

outputdir: ./output

select_time : False # keep it True, if you want to activate time_range
time_range:
  start_year : 1991
  end_year : 1991

ocean_drift:
  regions:
    - Global Ocean
    - Indian Ocean
    - Pacific Ocean
    - Atlantic Ocean
    - Arctic Ocean
    - Southern Ocean

    
ocean_circulation: #specify region and climatology time
  regions:
    Labrador Sea : DJF
    Irminger Sea : DJF
    Ross Sea : JJA
    Weddell Sea : JJA
    Gin Sea : DJF

compare_model_with_obs: True