model: IFS-NEMO 
exp: historical-1990
source: lra-r100-monthly

outputdir: ./output


select_time : False # keep it True, if you want to activate time_range
time_range:
  start_year : 1991
  end_year : 1991

ocean_drift:
  regions:
    - Global Ocean
    - Indian Ocean
    - Pacific Ocean
    - Atlantic Ocean
    - Arctic Ocean
    - Southern Ocean
    - Labrador Sea
    - irminger sea
    - ross sea
    - weddell Sea
    - gin sea
    
ocean_circulation: #specify region and climatology time
  regions:
    Global Ocean : yearly
    labrador sea : DJF
    irminger sea : DJF
    ross sea : JJA
    weddell Sea : JJA
    gin sea : DJF

compare_model_with_obs: True