sources:
  fdb:
    args:
      request:
        domain: g
        stream: oper
        class: ea
        type: an
        expver: "0001"
        param: t
        levtype: pl
        levelist: [1000]
        date: "20080101"
        time: "0000"
        step: 0
      data_start_date: "20080101T1200"
      data_end_date: "20080101T1200"
      aggregation: h
      timestep: h
      timestyle: date
    description: test FDB archive
    driver: gsv
    metadata: 
      fdb_path: /app/config.yaml
      source_grid_name: lon-lat

  fdb-auto:
    args:
      request:
        class: d1
        dataset: climate-dt
        activity: CMIP6
        experiment: hist
        generation: 1
        model: IFS-NEMO
        realization: 1
        resolution: standard
        expver: a0h3
        type: fc
        stream: clte
        date: 19900101
        time: "0000"
        param: tcc
        levtype: sfc
        step: 0
      data_start_date: auto
      data_end_date: auto
      aggregation: h
      timestep: h
      timestyle: date
    description: test FDB archive using new schema and auto dates
    driver: gsv
    metadata: 
      fdb_path: /app/config.yaml
      source_grid_name: lon-lat

  fdb-levels:
    args:
      request:
        domain: g
        stream: oper
        class: ea
        type: an
        expver: "0001"
        param: t
        levtype: pl
        levelist: [1000, 900, 800]
        date: "20080101"
        time: "0000"
        step: 0
      data_start_date: "20080101T1200"
      data_end_date: "20080101T1200"
      aggregation: h
      timestep: h
      timestyle: date
    description: test FDB archive
    driver: gsv
    metadata: 
      fdb_path: /app/config.yaml
      source_grid_name: lon-lat
      levels: [999.99, 899.99, 799.99]

  fdb-nolevels:
    args:
      request:
        domain: g
        stream: oper
        class: ea
        type: an
        expver: "0001"
        param: t
        levtype: pl
        levelist: [1000, 900, 800]
        date: "20080101"
        time: "0000"
        step: 0
      data_start_date: "20080101T1200"
      data_end_date: "20080101T1200"
      aggregation: h
      timestep: h
      timestyle: date
    description: test FDB archive
    driver: gsv
    metadata: 
      fdb_path: /app/config.yaml
      source_grid_name: lon-lat
