plugins:
  source:
  - module: intake_xarray
sources:
  short:
    args:
      chunks:
        time: 1
      urlpath:
      - ./AQUA_tests/models/IFS/short/IFS2d.tco79.nc
    description: original 2d output
    driver: netcdf
  long:
    args:
      chunks:
        time: 1
      urlpath:
      - ./AQUA_tests/models/IFS/long/regridded_r18x9.nc
    description: coarse IFS data 1y
    driver: netcdf
  
