plugins:
  source:
  - module: intake_xarray
sources:
  short:
    metadata:
      source_grid_name: tco79
    args:
      chunks:
        time: 1
      urlpath:
      - ./AQUA_tests/models/IFS/short/IFS2d.tco79.nc
    description: original 2d output
    driver: netcdf
  short_masked:
    metadata:
      source_grid_name: tco79-testmask
      fix_names: ifs-ci-test
    args:
      chunks:
        time: 1
      urlpath:
      - ./AQUA_tests/models/IFS/short/IFS2d.tco79.nc
    description: original 2d output
    driver: netcdf
  short_nn:
    metadata:
      source_grid_name: tco79-nn
    args:
      chunks:
        time: 1
      urlpath:
      - ./AQUA_tests/models/IFS/short/IFS2d.tco79.nc
    description: original 2d output
    driver: netcdf
  long:
    metadata:
      source_grid_name: lon-lat
    args:
      chunks:
        time: 1
      urlpath:
      - ./AQUA_tests/models/IFS/long/regridded_r18x9.nc
    description: coarse IFS data 1y
    driver: netcdf
  intake-esm-test:
    driver: intake_esm.esm_datastore
    description: Test Intake-ESM Catalog
    args:
      obj: ./config/machines/ci/catalog/IFS/test-esm.json
    metadata:
      source_grid_name: lon-lat
      query:
        experiment: historical
        frequency: hourly
  teleconnections:
    metadata:
      source_grid_name: lon-lat
    args:
      chunks:
        time: 1
      urlpath:
      - ./AQUA_tests/models/IFS/teleconnections/nao_test.nc
      - ./AQUA_tests/models/IFS/teleconnections/enso_test.nc
    description: teleconnections catalogue
    driver: netcdf
