name: dummy diagnostic test

on:
  # Not triggering the dummy diagnostic test on pull requests
  # in order to waste less resources
  # pull_request:
  #  branches: [ main, dev ]
  #  paths:
  #    - 'diagnostics/dummy/**'
  #    - 'tests/dummy/**'
  workflow_dispatch:
  #schedule:
  #  - cron: "0 3 * * 1" # Run every Monday night at 3AM UTC

jobs:
  dummy-diagnostic_test:
    if: contains(github.event.pull_request.labels.*.name, 'run tests') || contains(github.event.pull_request.labels.*.name, 'ready to merge')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Micromamba with diagnostic environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: dummy
          cache-downloads: true
          cache-environment: true
          condarc: |
            channels:
              - numba
              - conda-forge
          create-args: >-
              python=${{ matrix.python-version }}

# Run diagnostic tests
      - name: Download and setup dummy-diagnostic tests
        run: |
          ./tests/dummy/download_data_for_tests.sh
      
      - name: Set up AQUA
        run: |
          # Initialize the AQUA catalogue in the $HOME/.aqua folder
          aqua -vv install
          # Add the ci/cd catalogue
          aqua -vv add ci
          # Double check the catalogues
          aqua -vv list

      - name: Run dummy-diagnostic tests
        run: |
          python -m pytest -m dummy