name: tropical rainfall diagnostic test
# comment line is added to test all workflows with a common environment
on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'diagnostics/tropical_rainfall/**'
      - 'tests/tropical-rainfall/**'
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1" # Run every Monday night at 3AM UTC

permissions:
  contents: read

jobs:
  tropical-rainfall-diagnostic_test:
    if: contains(github.event.pull_request.labels.*.name, 'run tests') || contains(github.event.pull_request.labels.*.name, 'ready to merge')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Micromamba with diagnostic environment
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: 'latest'
          environment-file: environment.yml
          environment-name: tropical-rainfall
          cache-downloads: true
          cache-environment: false
          condarc: |
            channels:
              - numba
              - conda-forge
          create-args: >-
              python=${{ matrix.python-version }}

# Run diagnostic tests
      - name: Download and setup dummy-diagnostic tests
        run: |
          ./tests/tropical-rainfall/download_data_for_tests.sh

      - name: Set up AQUA
        run: |
          # Initialize the AQUA catalog in the $HOME/.aqua folder
          aqua -vv install github
          # Add the ci/cd catalog
          aqua -vv add ci
          # Double check the catalogs
          aqua -vv list

      - name: Run tropical-rainfall tests
        run: |
          pytest -v -m tropical_rainfall
