sources:
  monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: a0ef
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: 263101
        levtype: o2d
        step: 0
      data_start_date: '19900101'
      data_end_date: '19920101'
      aggregation: M
      savefreq: M
      timestep: H
      timestyle: step
      timeshift: Yes
    driver: gsv
    metadata:
      fdb_path: /scratch/project_465000454/iwagner/a0ef/config.yaml
      eccodes_path: 
        /project/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions
      source_grid_name: nemo-healpix
      variables: [263101, 263001, 263122, 263121, 263100]
  monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: a0ef
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: 187
        levtype: o3d
        step: 0
        levelist: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                  11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
                  21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
                  31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
                  41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
                  51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
                  61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
                  71, 72, 73, 74, 75]
      data_start_date: '19900101'
      data_end_date: '19920101'
      aggregation: M
      savefreq: M
      timestep: H
      timestyle: step
      timeshift: Yes
    driver: gsv
    metadata:
      fdb_path: /scratch/project_465000454/iwagner/a0ef/config.yaml
      eccodes_path: 
        /project/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions
      source_grid_name: nemo-healpix
      variables: [263500, 263501, 263505, 263506, 263507]